name: Generate Blog Metadata

on:
  push:
    branches:
      - "**"
    paths:
      - 'blog/**'

jobs:
  build-meta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Zig
        run: |
          curl -L https://ziglang.org/download/0.15.1/zig-x86_64-linux-0.15.1.tar.xz -o zig.tar.xz
          tar xf zig.tar.xz
          echo "$PWD/zig-x86_64-linux-0.15.1" >> $GITHUB_PATH

      - name: Build blog metadata
        working-directory: ${{ github.workspace }}
        run: zig build metadata

     
      - name: Commit updated metadata
        uses: EndBug/add-and-commit@v9
        with:
          add: 'blogsMetadata.json'
          message: 'Update blogsMetadata.json'
          author_name: GitHub Actions
          author_email: actions@github.com
          push: 'origin ${{ github.ref_name }}'
