name: Generate Blog Metadata

on:
  push:
    branches:
      - main
      - "**"

jobs:
  build-meta:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Zig
        run: |
          curl -L https://ziglang.org/download/0.15.1/zig-x86_64-linux-0.15.1.tar.xz -o zig.tar.xz
          tar xf zig.tar.xz
          sudo mv zig-x86_64-linux-0.15.1 /usr/local/zig
          export PATH="/usr/local/zig:$PATH"

      - name: Build blog metadata
        run: zig build metadata

      - name: Commit metadata
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add blogsMetadata.json
          git diff --quiet || git commit -m "Update blogsMetadata.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

